const icons={Leki:'💊',Nawodnienie:'💧',Dom:'🏠',Wizyta:'🧑‍⚕️',Urodziny:'🎂',Inne:'⚙️'};let category='Leki';let reminders=JSON.parse(localStorage.getItem('reminders')||'null')||[{name:'Weź pigułkę',category:'Leki',priority:'critical',time:'08:00 / 20:00',repeat:'Codziennie',voice:'Weź pigułkę, weź pigułkę'},{name:'Wypij wodę',category:'Nawodnienie',priority:'normal',time:'10:00 / 14:00 / 18:00',repeat:'Codziennie',voice:'Wypij wodę, wypij wodę'},{name:'Wizyta u lekarza',category:'Wizyta',priority:'high',time:'09:30',repeat:'15.04.2025',voice:'Wizyta u lekarza'},{name:'Przegląd samochodu',category:'Dom',priority:'low',time:'08:00',repeat:'01.06.2025',voice:'Przegląd samochodu'},{name:'Urodziny mamy',category:'Urodziny',priority:'normal',time:'12:00',repeat:'12.05.2025',voice:'Urodziny mamy'}];let history=JSON.parse(localStorage.getItem('history')||'[]'),activeReminder=null,audioCtx=null,editingIndex=null,deferredPrompt=null;
document.querySelectorAll('#categories button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#categories button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');category=b.dataset.cat});
function newReminder(){editingIndex=null;formTitle.innerHTML='← &nbsp; Dodaj przypomnienie';saveLabel.textContent='Zapisz przypomnienie';name.value='';time.value='20:00';repeat.value='Codziennie';voice.value='';priority.value='normal';category='Leki';document.querySelectorAll('#categories button').forEach((b,i)=>b.classList.toggle('selected',i===0));show('form')}
function editReminder(i){let r=reminders[i];editingIndex=i;formTitle.innerHTML='← &nbsp; Edytuj przypomnienie';saveLabel.textContent='Zapisz zmiany';name.value=r.name;time.value=(r.time.match(/\d{2}:\d{2}/)||['20:00'])[0];repeat.value=['Codziennie','Jednorazowo','Wybrane dni tygodnia'].includes(r.repeat)?r.repeat:'Jednorazowo';voice.value=r.voice||r.name;priority.value=r.priority||'normal';category=r.category||'Inne';document.querySelectorAll('#categories button').forEach(b=>b.classList.toggle('selected',b.dataset.cat===category));show('form')}
function deleteReminder(i){if(confirm('Usunąć przypomnienie „'+reminders[i].name+'”?')){reminders.splice(i,1);localStorage.setItem('reminders',JSON.stringify(reminders));render()}}
function show(id){['list','form','history','settings','alarm'].forEach(x=>document.getElementById(x).hidden=x!==id);if(id==='list')render();if(id==='history')renderHistory()}
function save(){let r={name:name.value.trim()||'Przypomnienie',category,priority:priority.value,time:time.value,repeat:repeat.value,voice:voice.value.trim()||name.value};reminders.unshift(r);localStorage.setItem('reminders',JSON.stringify(reminders));show('list')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){cards.innerHTML='';reminders.forEach((r,i)=>{let d=document.createElement('div');d.className='card '+(r.priority||'normal');d.innerHTML=`<div class="ico">${icons[r.category]||'🔔'}</div><b>${esc(r.name)}</b><div class="toggle">●</div><div class="meta">⌄ ${esc(r.repeat)}</div><div></div><div class="time">🔊 ${esc(r.time)}</div><div></div><div class="test-buttons"><button class="voice-test" onclick="testVoice(${i})">🔊 Test głosu</button><button class="alarm-test" onclick="testAlarm(${i})">🔔 Test alarmu</button></div><div class="card-actions"><button class="edit-btn" onclick="editReminder(${i})">✏️ Edytuj</button><button class="delete-btn" onclick="deleteReminder(${i})">🗑 Usuń</button></div>`;cards.appendChild(d)})}
function polishVoice(){let vs=speechSynthesis.getVoices();return vs.find(v=>/^pl[-_]/i.test(v.lang))||vs.find(v=>/pol/i.test(v.name))||null}function speak(text){return new Promise((res,rej)=>{if(!('speechSynthesis'in window))return rej();speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text),v=polishVoice();if(v)u.voice=v;u.lang='pl-PL';u.rate=.9;u.volume=1;u.onend=res;u.onerror=rej;speechSynthesis.speak(u)})}function beep(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();let n=audioCtx.currentTime;[0,.3,.6].forEach(t=>{let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=880;g.gain.setValueAtTime(.001,n+t);g.gain.exponentialRampToValueAtTime(.35,n+t+.02);g.gain.exponentialRampToValueAtTime(.001,n+t+.22);o.connect(g);g.connect(audioCtx.destination);o.start(n+t);o.stop(n+t+.24)});return new Promise(r=>setTimeout(r,1000))}catch(e){return Promise.resolve()}}
async function testVoice(i){try{await speak(reminders[i].voice)}catch(e){alert('Nie udało się uruchomić polskiego głosu.')}}function fillAlarm(r){activeReminder=r;alarm.className='alarm '+(r.priority||'normal');alarmIcon.textContent=icons[r.category]||'🔔';alarmName.textContent=r.name.toUpperCase();alarmTime.textContent=r.time;alarmRepeat.textContent=r.repeat;alarmVoice.textContent='🔊 „'+r.voice+'”'}async function testAlarm(i){fillAlarm(reminders[i]);show('alarm');await beep();try{await speak(reminders[i].voice)}catch(e){}}function previewVoice(){speak(voice.value).catch(()=>alert('Nie udało się uruchomić głosu.'))}async function previewAlarm(){let r={name:name.value,category,priority:priority.value,time:time.value,repeat:repeat.value,voice:voice.value};fillAlarm(r);show('alarm');await beep();try{await speak(r.voice)}catch(e){}}
function done(){if('speechSynthesis'in window)speechSynthesis.cancel();history.unshift({text:activeReminder?.name||alarmName.textContent,time:new Date().toLocaleString('pl-PL'),status:'Wykonane'});localStorage.setItem('history',JSON.stringify(history));show('list')}function snooze(){if('speechSynthesis'in window)speechSynthesis.cancel();alert('Przypomnienie odłożone o 10 minut (wersja demonstracyjna).');show('list')}function renderHistory(){hist.innerHTML=history.length?history.map(x=>`<p>✅ <b>${esc(x.text)}</b><br>${esc(x.time)} — ${esc(x.status||'Wykonane')}</p>`).join(''):'Brak wykonanych przypomnień.'}if('speechSynthesis'in window){speechSynthesis.getVoices();speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices()}render();

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});async function installApp(){if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true}else alert('Jeśli aplikacja jest już zainstalowana, znajdziesz ją na ekranie telefonu. W przeciwnym razie użyj menu przeglądarki i wybierz „Zainstaluj aplikację” lub „Dodaj do ekranu głównego”.')}if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
